import { Zone } from "../types";

export const firstFloorZones: Zone[] = [
  {
    id: "bank",
    name: "Bank of KidZania",
    description: {
      id: "Di sini adalah tempat untuk meningkatkan literasi keuangan! Sebagai klien, kalian akan dapat menggunakan berbagai layanan perbankan, seperti membuka rekening, mengaktifkan kartu debit, dan belajar tentang manfaat menabung. Cobalah untuk menggunakan ATM kidZo untuk menarik sejumlah uang! Kamu juga bisa menjadi seorang Bank Teller untuk membantu manager Bank dalam melalukan beberapa tugas!",
      en: "This is the place to improve your financial literacy! As a client, you will be able to use banking services, such as opening an account, activating a debit card and learning about the benefits of saving. Try using the kidZo ATM to withdraw some money! You can also be a Bank Teller who will help the Bank Manager perform several tasks.",
    },
    image: "establishment/Bank of Kidzania.png",
    top: 50,
    left: 31.6,
    width: 9.8,
    height: 5.1,
    activity: "activity/bank.JPG",
    video:
      "https://drive.google.com/file/d/1MMJBNo-p5RAKPTHAAAkxAzwlt870jVzp/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=9463a0eedbbe;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "miniroastery",
    name: "Mini Roastery ",
    description: {
      id: "Suatu produk harus dijaga kualitasnya. Kalian akan belajar tentang cara memproduksi kopi secara manual dan juga dengan mesin, serta menjaga mutu produk kopi. Di akhir kegiatan. kalian akan mendistribusikan kopi sesuai dengan pesanan warga kota kidZania!",
      en: "A product must maintain its quality. You will learn about how to produce coffee manually and also with machines, as well as how to maintain the quality of the coffee product. At the end of the activity, you will distribute coffee according to the orders from the citizens of KidZania!",
    },
    image: "establishment/Kapal Api.png",
    top: 55.15,
    left: 31.45,
    width: 10.1,
    height: 5,
    activity: "activity/kapalapi.JPG",
    video:
      "https://drive.google.com/file/d/13D2N2v3_IDTYz6LLqZhmNDJC7m1ESFqP/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=c25fbc6aa4b5;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "firestation",
    name: "Fire Station ",
    description: {
      id: "Apakah kalian ingin menjadi seorang pahlawan? Kantor Pemadam Kebakaran KidZania sedang mencari petugas pemadam kebakaran yang super pemberani! Kalian akan mendapatkan pelatihan profesional tentang tanggung jawab petugas pemadam kebakaran, latihan fisik, mendapatkan pengetahuan tentang nozel, belajar cara mencegah dan juga mengendalikan kebakaran. Ada kebakaran! Mari bergabung dengan pasukan dan padamkan apinya. Pantang pulang sebelum padam!",
      en: "Do you want to be a hero? Fire Station KidZania is looking for a Zuper brave firefighter! You will get professional training on firefighter responsibilities, physical training, gain knowledge of nozzles, learn how to prevent and control fires. Uh-oh! There's a fire! Let's join the troops and put out the fire!",
    },
    image: "establishment/LOGO Fire Station-01.png",
    top: 50,
    left: 41.8,
    width: 10,
    height: 10,
    activity: "activity/firestation.JPG",
    video:
      "https://drive.google.com/file/d/1hEt7JR3Q-v3C6kwSXy2_YYeVViNSkCv6/preview ",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=9536a49bf4d8;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "mainsquare",
    name: "Main Square ",
    description: {
      id: "Pengunjung dapat menikmati makanan dan kudapan yang dapat dibeli di Main Square Cafetaria",
      en: "Visitors can enjoy meals and snacks available at the Main Square Cafeteria.",
    },
    image: "establishment/Main Square.png",
    top: 37.1,
    left: 31.5,
    width: 20.9,
    height: 12.3,
    activity: "activity/mainsquare.JPG",
    tags: ["ParentZ", "TeenZ", "ChildZ"],
  },

  {
    id: "cafetaria",
    name: "Cafetaria ",
    description: {
      id: "Pengunjung dapat Membeli makanan dan kudapan yang akan dinikmati di Cafetaria atau Main Square",
      en: "Visitors can buy meals and snacks to enjoy in the Cafeteria or Main Square.",
    },
    image: "establishment/Main Square.png",
    top: 30,
    left: 32.8,
    width: 13,
    height: 7.5,
    activity: "activity/cafetaria.JPG",
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    menu: "menu/cafetaria.jpg",
  },
  {
    id: "culinary",
    name: "Culinary School",
    description: {
      id: "Jadilah koki yang kool untuk membuat mahakarya! Kalian akan membuat makanan melalui persiapan hingga menghias/dekorasi. Uleni adonan, cetak menjadi bentuk yang lucu, hiasi adonan dan panggang. Voila… Kue kalian sudah siap disantap!",
      en: "Be a kool chef and make a masterpiece! You will create your own meals through preparing, cooking, and decorating. Knead the dough, mold it into cute shapes, decorate half-baked dough, and bake it. Voila… Your cookies are ready to eat!",
    },
    image: "establishment/Fiber Creme.png",
    top: 23.5,
    left: 41,
    width: 10,
    height: 7.8,
    activity: "activity/fibercreme.JPG",
    video:
      "https://drive.google.com/file/d/1riN6z8w4oclD05QC87paMifB8FHIk7B6/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=64624f95c04b;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "stasiunradio",
    name: "Stasiun Radio",
    description: {
      id: "Belajar menjadi Penyiar Radio! Sebarkan kabar baik dan update terbaru tentang kota KidZania ke semua citiZen.",
      en: "Learn to be a Radio Host! Spread the good news and latest updates about KidZania city to all citiZens.",
    },
    image: "establishment/GenFM (2).png",
    top: 19,
    left: 47.5,
    width: 10.5,
    height: 5,
    activity: "activity/radio.JPG",
    video:
      "https://drive.google.com/file/d/1KtbLuot-HHaV0Z73XoD1SuHSbbnHhIve/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=7ecb8aa15f42;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "commercialstudio",
    name: "Commercial Studio",
    description: {
      id: "Selalu up-to-date dengan tren masa kini! Buat konten menarik tentang yang informatif tentang berbagai macam topik. Kalian bisa menjadi pembawa acara yang mengulas sebuah produk ataupun bisa juga menjadi seorang kameramen. Kool, kan?",
      en: "You will know the procedures, techniques, and machinery for making aromatherapy oils, then you will distribute them to Minimarket.",
    },
    image: "establishment/commercial.png",
    top: 23.5,
    left: 51,
    width: 7,
    height: 8,
    activity: "activity/commer.png",
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=c86f8a77d9d7;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "bkz",
    name: "B-Kidzanian",
    description: {
      id: "Jadilah bagian dari KidZania CitiZen dapatkan PaZZport dan nikmati manfaatnya selama kunjungan anda di KidZania",
      en: "Become part of the KidZania CitiZens, get a PaZZport, and enjoy its benefits during your visit to KidZania.",
    },
    image: "establishment/BKZ.png",
    top: 26.6,
    left: 58.2,
    width: 10.3,
    height: 4.5,
    activity: "activity/bkz.png",
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=6b382bc92662;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "firstaid",
    name: "First Aid Center",
    description: {
      id: "Kalian akan belajar bagaimana melakukan pertolongan pertama, mengantisipasi situasi tertentu yang berpotensi bahaya, dan langkah yang tepat sampai ada penyelamatan lebih lanjut (perawatan pra-rumah sakit).",
      en: "You will learn how to perform first aid rescue, certain potentially dangerous situations, and appropriate conduct while waiting for further rescue (prehospital care).",
    },
    image: "establishment/First Aid.png",
    top: 19.2,
    left: 58.5,
    width: 4.7,
    height: 7.3,
    activity: "activity/first aid.JPG",
    video:
      "https://drive.google.com/file/d/1W1MXEtnxqggVvDdBrNERJkcAOFZYuk73/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=47611cd1b011;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "internetcenter",
    name: "Internet Center",
    description: {
      id: "Apa jadinya kehidupan jika tanpa internet? Di sini, kalian akan mendapat pengalaman langsung dalam memelihara jaringan internet Kota KidZania. Pahami cara kerja internet, ikuti prosedur kerja yang ditelah diinstruksikan agar dapat memberikan fasilitas internet yang lancar untuk warga Kota KidZania. ",
      en: "What would life be like without the internet? Here, you will have a hands-on experience in maintaining the internet network of KidZania City. Understand how the internet works, follow the work procedures that have been instructed to provide a smooth internet facility for the residents of KidZania City.",
    },
    image: "establishment/LogoBiznet_full.png",
    top: 19.2,
    left: 64,
    width: 4,
    height: 7.1,
    activity: "activity/internetcenter.JPG",
    rotate: true,
    video:
      "https://drive.google.com/file/d/1H19yT2Cu1MrX7NBAczgziEtNkZl7Jh0r/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=4a3701528fc2;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "crimescene",
    name: "Crime Scene",
    description: {
      id: "Ada perampokan di Toko Emas! Segera ke TKP untuk kumpulkan bukti. Kembali ke kantor dan analisis semua bukti untuk menyelesaikan kasus.",
      en: "A robbery happened at the Gold Store! Head to the crime scene to collect evidence. Return to the office and analyze the findings to solve the case.",
    },
    image: "establishment/UBS Gold.png",
    top: 19.5,
    left: 69,
    width: 7.1,
    height: 4.5,
    activity: "",
    rotate: false,
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=77296c7252cb;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "waterresearch",
    name: "Water Research",
    description: {
      id: "Ingin mengetahui dari mana air minum kita berasal? Kalian akan menjadi seorang Hidrogeolog. Pelajari pentingnya air bagi kehidupan, menggali lokasi potensial untuk mencari sumber air, lindungi sumber air, dan ukur kualitas air yang akan diolah menjadi air minum.",
      en: "Did you know where our drinking water comes from? You will perform the role of Hydrogeologist. Learn the importance of water, investigate potential sites to find water source, protect the water sources, and measure the water quality that will be processed to be drinking water.",
    },
    image: "establishment/water reasearch.png",
    top: 24.2,
    left: 69,
    width: 7.5,
    height: 7,
    activity: "activity/waterresearch.JPG",
    rotate: false,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=fe9923d76f45;Asia/Jakarta;HH:mm;en-US",
  },
  //end of daerah tengah
  //start from pizzania going to vizion
  {
    id: "pizza",
    name: "Pizzania",
    description: {
      id: "Apakah kalian sudah pernah mencoba pizza terenak di kota ini? Kalian akan tahu resep rahasianya jika kalian membuatnya sendiri. Ayo membuat pizza di PiZZania!",
      en: "Have you tried the best pizza in town? You will know the secret recipe if you make your own. Let's make a masterpiece at PiZZania!",
    },
    image: "establishment/Pizzania.png",
    top: 58,
    left: 4,
    width: 19,
    height: 9,
    activity: "activity/pizzania.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1iw-jk-GEbBsiI7i-nsQ67hStJaMEhIna/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=4f173e841927;Asia/Jakarta;HH:mm;en-US",
    menu: "menu/pizzania.jpg",
  },
  {
    id: "kacamata",
    name: "Vizion",
    description: {
      id: "Apakah kalian ingin tahu seberapa jelas penglihatan kalian? Dalam kegiatan ini kalian akan mendapatkan pemeriksaan mata. Kalian juga bisa menjadi seorang dokter mata yang akan memberikan konsultasi kepada pasien. Kool, kan?",
      en: "Do you want to know how clearly you can see? Join this activity to get an eye examination. You can also become an optometrist who will provide consultations to a patient. Kool, right?",
    },
    image: "establishment/Asset 7@5x-8.png",
    top: 53.5,
    left: 12,
    width: 10.8,
    height: 4.1,
    activity: "",
    rotate: false,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=abfe8c4a7f47;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "actingacademy",
    name: "Acting Academy",
    description: {
      id: "Kalian akan mempelajari keterampilan akting dasar seperti ekspresi fisik, teknik suara, dan pemblokiran panggung untuk menjadi aktor dan tampil di Teater.Untuk membuat hari kalian lebih seru, ikutilah Parade bersama tim Marching Band!",
      en: "You will learn basic acting skills such as corporal expression, voice techniques, and stage blocking to become an actor and perform at the KidZania Metropolitan Theater. To make your day more exciting, pleeZ join the City Parade with the Marching Band team!",
    },
    image: "establishment/Acting Academy.png",
    top: 49,
    left: 12,
    width: 11,
    height: 4.4,
    activity: "activity/Acting Academy.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1PnEIoA3nvxaxXZ-DRVrCa-SVMgL434g_/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=a69077146b50;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "Theater",
    name: "Metropolitan Theater",
    description: {
      id: "Salah satu tempat paling seru di KidZania menanti kalian! Kalian akan sangat terhibur oleh berbagai pertujukan spektakuler. Jadi, duduklah, santai, dan nikmati pertunjukannya! Jika kalian beruntung, kalian juga bisa bertemu dan menyapa RightZKeepers KidZania!",
      en: "One of the most exciting places in KidZania is waiting for you! You will be fully entertained by spectacular performances. If you're lucky, you can meet and greet our RightZKeepers! So, sit back, relax, and enjoy the show!  Additional Activities/Events: Birthday party Ceremonial events Coaching Clinic Fashion Show and many more",
    },
    image: "establishment/theatree@5x-8.png",
    top: 38.5,
    left: 9,
    width: 15,
    height: 9,
    activity: "activity/Acting Academy.JPG",
    rotate: false,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=8d091e2dd8ea;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "fashionstudio",
    name: "UBS Fashion Studio",
    description: {
      id: "Kalian ingin tahu bagaimana rasanya menjadi Perancang Perhiasan? Ini adalah tempat yang sempurna untuk kalian! Ekspresikan kreativitas kalian dengan merangkai manik-manik indah lalu tunjukkan pada dunia. Kalian juga bisa menjadi seorang Model untuk belajar berjalan seperti model profesional dan berpose. Bagian yang paling kool, adalah Anda akan melakukan Fashion Show di Teater.",
      en: "Do you want to feel what it's like to be a Jewelry Designer? This is the perfect place for you! Express your creativity by stringing beautiful beads then show it to the world. You can also be a Runway Model to learn to walk like a professional model and strike a pose. The koolest part, is you will be performing a Fashion Show at the Theater.",
    },
    image: "establishment/UBS Gold 2.png",
    top: 32.5,
    left: 9,
    width: 13.7,
    height: 6,
    activity: "activity/ubsjewelry.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1J4YomCp1k5gtp3jSt0MT8i548yPe-8KT/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=974c10743bc7;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "onlineshop",
    name: "eaZy Shop",
    description: {
      id: "Ada banyak keuntungan yang didapatkan ketika berjualan lewat platform digital. Mari kita pelajari bagaimana cara mempromosikan produk dalam live! Kamu bisa menjadi seorang Penyiar Live Shopping yang asyik, mengulas dan mendemonstrasikan produk, serta mempromosikannya di platform digital. Kamu juga bisa belajar mengatur siaran dan menjadi seorang Operator Live Shopping yang profesional!",
      en: "You can be a fun Live Shopping Host, try out products, and promote them online. You will also learn how to manage your broadcasts and become a Live Shopping Operator like a pro!",
    },
    image: "establishment/eaZy Shop.png",
    top: 28,
    left: 9,
    width: 13.7,
    height: 4.8,
    activity: "",
    rotate: false,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=463780b1e930;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "archeologicalsite",
    name: "Archeological Site",
    description: {
      id: "Kalian akan menjadi arkeolog yang mempelajari masa lampau manusia dengan mengamati artefak yang kalian temukan di situs, serta sebagai ahli paleontologi kalian akan mengembangkan gambaran masa lampau dengan mengamati dan menjelajahi fosil yang kalian temukan di situs.",
      en: "You will be an archaeologist studying the human past by observing the artifacts you found at the site as well as Paleontologist to develop unified picture of the past by observing and exploring fossil you found on site.",
    },
    image: "establishment/archeolog.png",
    top: 22.5,
    left: 10.5,
    width: 12.2,
    height: 5.5,
    activity: "activity/archeolog.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1_Furg2m7qfANOf3fz4oEf4TlzOkVF4bs/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=8b76de440e29;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "urbanforest",
    name: "Urban Forest",
    description: {
      id: "Kalian akan menjadi seorang Rimbawan yang kool! Tingkatkan pemahaman tentang pentingnya alam bagi kehidupan dan pelajari cara merawatnya.",
      en: "You will be a kool Forester! Increase understanding of the importance of nature for life and learn how to take care of them.",
    },

    image: "establishment/hutan kota.png",
    top: 17,
    left: 25.8,
    width: 13.2,
    height: 6,
    activity: "activity/urbanforest.JPG",
    rotate: false,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=5e4c30153c75;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "hospital",
    name: "Medikal Center",
    description: {
      id: "Obat menyembuhkan penyakit, tetapi hanya dokter yang bisa menyembuhkan pasien. Rumah Sakit KidZania sedang mencari dokter yang kool! Ayo daftar dan pilih peran yang kalian inginkan. Sebagai Ahli Bedah, kalian akan melakukan berbagai jenis operasi seperti bedah jantung, bedah hati, dan lain sebagainya. Sebagai Paramedis, kalian akan belajar tentang pertolongan pertama, melakukan pemeriksaan kesehatan pada pasien, dan yang paling kool adalah kalian dapat membantu dan menjemput orang yang terluka dengan ambulans! Sebagai Perawat Bayi, kalian akan belajar cara merawat bayi yang baru lahir. Sebagai Murid/Peserta Magang, kalian akan berperan sebagai penyandang disabilitas untuk memahami perasaan dan kebutuhan mereka serta meningkatkan empati kepada mereka. Percayalah, kalian akan belajar banyak di sini!",
      en: "Visitors can take on various medical roles such as performing surgery on dummies, providing first aid, caring for newborns, and learning empathy through different responsibilities.",
    },

    image: "establishment/MediKal.png",
    top: 3.5,
    left: 61.5,
    width: 16,
    height: 9.7,
    activity: "activity/hospital.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1ZOieYb1Jy3VVRw1S2oTuYgosaCGWVwdc/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=523d1935ae44;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "sciencelab",
    name: "Yakult's Science Lab",
    description: {
      id: "Sebagai seorang ilmuwan, kalian akan memahami sistem pencernaan, mengetahui berapa banyak bakteri baik yang dibutuhkan tubuh, dan juga meneliti bakteri menggunakan mikroskop.",
      en: "As a scientist, you will understand the digestive system, find out how many good bacteria the body needs, and examine bacteria using a microscope.",
    },

    image: "establishment/Yakult.png",
    top: 4.2,
    left: 78.5,
    width: 8,
    height: 8.9,
    activity: "activity/yakult.JPG",
    rotate: true,
    video:
      "https://drive.google.com/file/d/1xDGje_onrE9FKpQaNyfg2-XH_sgzPM3C/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=d596af9487b2;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "citytour",
    name: "KAI's City Tour",
    description: {
      id: "Naik trem wisata dan bersiap untuk bertualang! Pemandu wisata kami akan membawa kalian berkeliling kota KidZania dengan naik trem wisata kota. Cari tahu tentang sejarah dan bangunan-bangunan khas yang ada di KidZania. Selamat berwisata!",
      en: "Hop on the tram and prepare for an adventure! Our Tour Guide will take you around the city of KidZania by riding a tour bus. Find out about the history and landmarks of KidZania. Enjoy the tour!",
    },

    image: "establishment/KAI.png",
    top: 14.2,
    left: 84,
    width: 11,
    height: 8.5,
    activity: "activity/kai.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1pcRRv51Ur3gpUbQZ1KNJkVcl-GoNakxb/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=33fae8e30776;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "windowwash",
    name: "Zparkling",
    description: {
      id: "Menjaga kebersihan kota KidZania sangat penting agar aktivitas sehari-hari nyaman. Kalian akan bekerja membersihkan jendela kaca establishment lain di KidZania. Pahami pentingnya menjaga kebersihan lingkungan sekitar.",
      en: "Maintaining the cleanliness of KidZania is very important for a comfortable daily experience. You will work to clean the glass windows of other establishments in KidZania. Recognize the importance of maintaining a clean surrounding environment.",
    },

    image: "establishment/window wash.png",
    top: 22.8,
    left: 84,
    width: 6.8,
    height: 6,
    activity: "activity/Zparkling.JPG",
    rotate: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=a52d697e9be7;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "bif",
    name: "Building in Flame",
    description: {
      id: "Pengunjung dapat memadamkan api pada gedung hotel yang terbakar",
      en: "Visitors can put out a fire in a burning hotel building.",
    },

    image: "establishment/LOGO Fire Station-01.png",
    top: 28.5,
    left: 84,
    width: 12,
    height: 9,
    activity: "activity/firestation.JPG",
    rotate: false,
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=9536a49bf4d8;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "crackerfactory",
    name: "Finna's Cracker Factory",
    description: {
      id: "Kalian akan memahami prosedur dan teknik dalam membuat kerupuk.",
      en: "You will understand the procedure, technique and machinary in making crackers.",
    },

    image: "establishment/Finna.png",
    top: 36.5,
    left: 60,
    width: 10.5,
    height: 4.5,
    activity: "activity/finna.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1EDfxs13Lh0bpqcdia1F76b4op8EWEYN_/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=bbe58410e21c;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "csi",
    name: "UBS's Criminal Scene Investigation & Police Station",
    description: {
      id: "'Police Station' Kota KidZania membutuhkan seorang pahlawan! Kami mencari Polisi yang akan menjaga kota agar tetap aman. Kalian akan membantu mengendalikan kerumunan saat terjadi kebakaran di sebuah gedung. Kalian juga akan menyelidiki dan memecahkan kasus untuk menemukan tersangka. 'CSI' Ada perampokan di Toko Emas! Segera ke TKP untuk kumpulkan bukti. Kembali ke kantor dan analisis semua bukti untuk menyelesaikan kasus.",
      en: "'Police Station' KidZania city needs a hero! We are looking for an Officer who will keep the city safe. You will help control the crowd in the event of a fire in a nearby building. You will also investigate and solve a case to find the suspect. 'CSI' There's a robbery at a Gold Shop! You should go to the crime scene immediately! Collect evidence, go back to the office, then analyze all of the evidence to solve the case.",
    },
    image: "establishment/UBS Gold 2.png",
    top: 41.4,
    left: 60,
    width: 10,
    height: 6.5,
    activity: "activity/ubspolice.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1z3RZVtg6-gcMtzLm9zWmtXx8_6jcwXOd/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=9bd0e47adcc6;Asia/Jakarta;HH:mm;en-US",
    fib2: "https://www.fourz.net/Operations/CensusDisplay?p=77296c7252cb;Asia/Jakarta;HH:mm;en-US",
    fibLabel: "Police Station",
    fib2Label: "CSI",
  },
  {
    id: "university",
    name: "Univerzity",
    description: {
      id: "Sebagai mahasiswa, kalian akan bergabung dalam kelompok belajar dalam bereksperimen sederhana untuk mendapatkan gelar Sarjana yang berbasis STEM (Sains, Teknologi, Teknik dan Matematika).",
      en: "As a student, you will join study group and experiment with building simple robots to obtain a Bachelor Degree in STEM (Science, Technology, Engineering, and Mathematics).",
    },

    image: "establishment/KZ Univ.png",
    top: 47.8,
    left: 60,
    width: 13,
    height: 4,
    activity: "activity/kzuniv.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1sdE6rSIe41zEfpSj84F5EVugChc7ETDf/preview",
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=e0dc811900d8;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "drivingsim",
    name: "Mitsubishi's Driving Simulation",
    description: {
      id: "Ingin membuat SIM dan membawanya pulang? Sebelum itu, kalian harus lulus tes mengemudi dengan simulator canggih untuk menunjukkan kompetensi kalian dalam mengendarai kendaraan bermotor. Tes mengemudi ini akan membantu kalian memahami rambu lalu lintas agar lebih tertib dalam berkendara. Berkendara dengan aman, ya, kals!",
      en: "Get your own driving license and take it home! But first, you have to pass a driving test on a sophisticated simulator to demonstrate your competence in operating a vehicle. This driving test will help you understand traffic signs in order to make us more orderly in driving. Drive safe, kals!",
    },

    image: "establishment/logo kidzania motor@5x-8.png",
    top: 52,
    left: 60,
    width: 10,
    height: 8,
    activity: "activity/drivingsim.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1PXrtKXHDDTnaCSWaRwfbH1mYfWjvmMNO/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=0563902d1713;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "steelstructure1",
    name: "Construction Site & Steel Structure",
    description: {
      id: "Apakah kalian takut ketinggian? Taklukkan ketakutanmu! Berjalan melalui struktur baja dan melewati berbagai rintangan.",
      en: "Are you afraid of heights? Conquer your fears! Walk through the steel structure overcoming obstacles and do different tasks.",
    },

    image: "establishment/Asset 41@300x-8.png",
    top: 52,
    left: 70.5,
    width: 6.5,
    height: 7.7,
    activity: "activity/construction.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/17qCQ-uuxEC4jqtMuNABghgtkT4oHDnxT/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ", "Toddler"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=85e69cde4740;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "steelstructure2",
    name: "Construction Site & Steel Structure",
    description: {
      id: "Apakah kalian takut ketinggian? Taklukkan ketakutanmu! Berjalan melalui struktur baja dan melewati berbagai rintangan.",
      en: "Are you afraid of heights? Conquer your fears! Walk through the steel structure overcoming obstacles and do different tasks.",
    },

    image: "establishment/Asset 41@300x-8.png",
    top: 48.5,
    left: 73.2,
    width: 14,
    height: 7,
    activity: "activity/construction.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/17qCQ-uuxEC4jqtMuNABghgtkT4oHDnxT/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ", "Toddler"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=85e69cde4740;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "earlystimulation",
    name: "Alamii's Early Stimulation",
    description: {
      id: "Orang tua dan anak-anak dapat menikmati berbagai permainan sensorik di area yang dirancang khusus untuk balita ini. Stimulasi dini dapat meningkatkan perkembangan otak balita.",
      en: "Explore everrything all by yourself! Parents and the kids can enjoy a variety of sensory play in this specially designed soft-play area for toddlers. Early stimulation can boost toddler's brain development.",
    },

    image: "establishment/Alamii.png",
    top: 60,
    left: 90,
    width: 7,
    height: 6,
    activity: "activity/alamii.JPG",
    rotate: false,
    tags: ["ParentZ", "Toddler"],
  },
  {
    id: "vitasdinner",
    name: "Vita's Dinner",
    description: {
      id: "Siapkan sarapan, makan siang atau makan malam untuk orang tua kalian!",
      en: "Prepare breakfast, lunch or dinner for your parents!",
    },

    image: "establishment/Vitas dinner.png",
    top: 66,
    left: 90,
    width: 7.4,
    height: 4,
    activity: "activity/vitasdinner.JPG",
    rotate: false,
    tags: ["ParentZ", "Toddler"],
  },
  {
    id: "openstage",
    name: "Chika's Open Stage",
    description: {
      id: "Mau nonton pertunjukkan seru? Ayo berkumpul di Chika's Spotlight! Di sini kalian dapat melihat pertunjukkan boneka tangan, storytelling, atau jika beruntung kalian bisa meet and greet dengan RightZKeepers KidZania!",
      en: "Are you up for a fun and amazing show? Let's gather at Chika's Spotlight! You can watch many shows, such as puppet shows, storytelling, or if you are lucky enough, you can meet and greet with our RightZKeepers!",
    },

    image: "establishment/Asset 23@5x-8.png",
    top: 74.5,
    left: 68,
    width: 15.9,
    height: 9,
    activity: "activity/chikaspotlight.JPG",
    rotate: false,
    tags: ["ParentZ", "Toddler"],
  },
  {
    id: "drivingtrack",
    name: "Mitsubishi's Driving Track",
    description: {
      id: "Pasang sabuk pengaman! Kalian akan mengemudi di jalur berkendara dan mempelajari rambu-rambu lalu lintas. Mengemudi dengan aman ya, kals!",
      en: "Put on your seatbelt! You will drive on a driving track and learn the road sign. Drive safely, kals!",
    },

    image: "establishment/logo kidzania motor@5x-8.png",
    top: 57,
    left: 77.8,
    width: 10.6,
    height: 11,
    activity: "activity/drivingtrack2.JPG",
    rotate: false,
    tags: ["ParentZ", "Toddler"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=b682785739d3;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "minimarket",
    name: "Alfamart",
    description: {
      id: "Yuk, belajar melayani pelanggan.. Di sini, kalian bisa bekerja sebagai Asisten Toko, Kasir atau Kru Toko yang akan memahami tentang pelayanan pelanggan. Kalian juga dapat berperan sebagai pelanggan/pembeli. Kalian akan mendapatkan voucher untuk berbelanja apa pun yang kalian inginkan!",
      en: "Let's learn how to achieve service excellence! You will work as a Store Assistant, Cashier, or Store Crew. You can also act as a customer/buyer. You will get vouchers to shop for whatever you want!",
    },
    image: "establishment/Alfamart.png",
    top: 65.8,
    left: 65.2,
    width: 10.5,
    height: 8.5,
    activity: "activity/alfamart.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/1cyP-OKpXimmfN7Xp9Ci20k-8CD83G0kC/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=c75e8a8c7c51;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "laundry",
    name: "SoKlin's Laundry",
    description: {
      id: "Mari kita kenali cara mecuci dan menyetrika pakaian! Kalian akan bekerja sebagai petugas laundry yang menangani proses pencucian, penyetrikaan, pelipatan, pengambilan dan pengantaran pakaian pelanggan. Ayo buat warga Kota KidZania berpenampilan lebih rapi dan kool!",
      en: "Maintaining the cleanliness of KidZania is very important for a comfortable daily experience. You will work to clean the glass windows of other establishments in KidZania. Recognize the importance of maintaining a clean surrounding environment.",
    },

    image: "establishment/soklin.png",
    top: 66,
    left: 42.6,
    width: 6,
    height: 8.5,
    activity: "activity/Laundry.JPG",
    rotate: false,
    video:
      "https://drive.google.com/file/d/11XOx7PXpxrn6XBxdQsYPARtuqqj5J2nm/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=882c091cea39;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "deptstore",
    name: "Zentral Gallery",
    description: {
      id: "Kalian bisa membeli suvenir yang kool dan membayar menggunakan kidZo!",
      en: "You can use kidZo to buy kool souvenirs.",
    },

    image: "establishment/Zentral Gallery.png",
    top: 66,
    left: 36,
    width: 6.1,
    height: 8.5,
    activity: "activity/deptstore.JPG",
    rotate: false,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=ebfe2e668c2d;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "kidzaniashop",
    name: "Kidzania Shop",
    description: {
      id: "Dapatkan produk KidZania kesukaan anda di KidZania Shop!",
      en: "Get your favorite KidZania merchandise at the KidZania Shop!",
    },
    image: "establishment/KZ Shop.png",
    top: 71.3,
    left: 27.9,
    width: 7.9,
    height: 7,
    activity: "activity/kzshop.JPG",
    rotate: false,
  },
  {
    id: "mediapos",
    name: "Canon's MediaPOS",
    description: {
      id: "Pengunjung dapat membeli foto - foto kenangan favorit selama kunjungan di KidZania",
      en: "Visitors can purchase their favorite photo memories from their visit to KidZania.",
    },

    image: "establishment/Media Pos (Canon).png",
    top: 66,
    left: 27.8,
    width: 8.2,
    height: 5,
    activity: "activity/mediapos.JPG",
    rotate: false,
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=ef3a883c20e2;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "imigrasi",
    name: "Imigrasi",
    description: {
      id: "Tempat keluar pengunjung untuk memasuki kota KidZania",
      en: "Visitors' exit point to enter the city of KidZania.",
    },

    image: "establishment/Imigrasi.png",
    top: 66,
    left: 19.2,
    width: 8.3,
    height: 8.3,
    activity: "",
    rotate: false,
  },
  {
    id: "Airport",
    name: "Airport",
    description: {
      id: "Akses pengunjung untuk memasuki kota Kidzania",
      en: "Visitors' access point to enter the city of KidZania.",
    },
    image: "establishment/travelooka@5x-8.png",
    top: 74.5,
    left: 35.7,
    width: 31.8,
    height: 15,
    activity: "activity/airport.JPG",
    rotate: false,
  },
];
