import { Zone } from "../types";

export const secondFloorZones: Zone[] = [
  {
    id: "tvstation",
    name: "TV Station",
    description: {
      id: "Kalian akan merekam acara televisi, menjadi bagian dari kru produksi atau bisa menjadi bintang tamu.",
      en: "You will record a television show, be part of the production crew or be the star of the show.",
    },
    image: "establishment/RTV.png",
    top: 25.8,
    left: 59.5,
    width: 16.5,
    height: 12.5,
    activity: "activity/rtv.JPG",
    video:
      "https://drive.google.com/file/d/1qOPx9GOLhSUB7QseX6UKTp1vKKzq7Zll/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=abba8e7f167c;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "noodlefactory",
    name: "Noodle Factory",
    description: {
      id: "Mari kita kenali cara membuat mie instan paling enak! Bekerjalah sebagai produsen mie dan kalian akan memahami proses pembuatan mie dari adonan hingga proses pengemasan. Dapatkan 1 bungkus Indomie gratis!",
      en: "Let's get to know how to make the most delicious instant noodles in town! Work as a noodle manufacturer and you will understand the noodle making process from dough to packaging process. Get 1 free Indomie as a giveaway!",
    },
    image: "establishment/Indomie.png",
    top: 38.7,
    left: 62.9,
    width: 12.9,
    height: 6.5,
    activity: "activity/indomie.JPG",
    video:
      "https://drive.google.com/file/d/1ZHf1viKKZQw54ys8Giszi34xfk_o85Va/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=9f9946408153;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "hampersstudio",
    name: "Hampers Studio",
    description: {
      id: "Hadiah selalu jadi kejutan spesial di momen istimewa. Di sini kalian akan bekerja sebagai visual merchandiser yang menyiapkan dan menata kado. Pahami alat dan bahan yang digunakan untuk membuat suatu bingkisan kado, terima pesanan dan bekerjalah, kreasikan kado semenarik mungkin agar mengesankan penerima!",
      en: "Gifts always become special surprises on special occasions. Here you will work as a visual merchandiser who prepares and arranges gifts. Understand the tools and materials used to create a gift package, take orders and work, create gifts as attractively as possible to impress the recipient!",
    },
    image: "establishment/logo gift shop@4x-01.png",
    top: 45.8,
    left: 62.9,
    width: 12.9,
    height: 5,
    activity: "activity/hampers.JPG",
    video:
      "https://drive.google.com/file/d/1tZZioL0bgrDGjb7YeQjTciYlq821WWrY/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=b2751bb6dedf;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "aviation",
    name: "Aviation",
    description: {
      id: "Kai! Kami mencari Pilot berbakat untuk menerbangkan pesawat di akademi pelatihan kami. Pelajari semua yang perlu kalian ketahui tentang menerbangkan Airbus A-330 asli menggunakan simulator penerbangan, jalur penerbangan nyata, dan rintangan di sepanjang jalan. Untuk pengalaman lainnya, kalian bisa mencoba menjadi Cabin Crew! Kalian akan memberikan demonstrasi keamanan pesawat terbang dan memenuhi kebutuhan penumpang. Keren, kan?",
      en: "Kai! This is your Captain speaking we are looking for talented Pilots to fly an aircraft at our training academy. Learn everything you need to know about flying a real Airbus A-330 using the flight simulator, real flight paths and obstacles along the way. For another experience, you can try being a Cabin Crew! You will give demonstrations of aircraft safety and fulfill the needs of passengers. Kool, right?",
    },
    image: "establishment/Aviation.png",
    top: 51,
    left: 62.9,
    width: 12.9,
    height: 6,
    activity: "activity/aviation.JPG",
    video:
      "https://drive.google.com/file/d/1pUvxhrdD-bywehPTbEnzvhnxg0MrgCC_/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=b5b95143e63b;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "sportstudio",
    name: "Sport Studio",
    description: {
      id: "Tak hanya bekerja, di Kota KidZania, olahraga sangat penting dilakukan untuk menjaga badan tetap sehat dan bugar. Kalian bisa melakukan beragam latihan fisik di Studio Olahraga! Ayo biasakan gaya hidup sehat dengan berolahraga!",
      en: "Not only working, in KidZania City, sports are very important to maintain a healthy and fit body. You can do various physical exercises in the Sports Studio! Let's get used to a healthy lifestyle by exercising!",
    },
    image: "establishment/logo sport studio.png",
    top: 57,
    left: 54.5,
    width: 8.7,
    height: 7,
    activity: "activity/sportstudio.JPG",
    video:
      "https://drive.google.com/file/d/1GGmzqJBXGwY1pkSfIb9PjVYS53ovIg0D/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=5a4064545dcf;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "biscuitfactory",
    name: "Biscuit Factory",
    description: {
      id: "Semua orang suka biskuit, kan? Di sini kalian akan belajar tentang proses pembuatan biskuit yang enak. Kuasai tekniknya dan jadilah seorang pembuat biskuit yang handal!",
      en: "Everyone loves biscuits, right? Here you will learn about the process of making delicious biscuits. Master the technique and become a skilled biscuit maker!",
    },
    image: "establishment/biscuit.png",
    top: 64,
    left: 54.5,
    width: 8.7,
    height: 7.5,
    activity: "activity/Biscuit Factory.JPG",
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=3a00bb726b4d;Asia/Jakarta;HH:mm;en-US",
    tags: ["ParentZ", "TeenZ", "ChildZ"],
  },
  {
    id: "karaoke",
    name: "Karaoke",
    description: {
      id: "Ayo bersenang-senang! Ini adalah tempat yang tepat untuk kalian mengekspresikan diri! Kalian dapat bernyanyi dan menari dengan orang tua dan teman-teman kalian.",
      en: "Let's have some fun! This is the perfect place to express yourself! You can sing and dance with your friends.",
    },
    image: "establishment/Asset 1@8x-8.png",
    top: 66,
    left: 36,
    width: 10.5,
    height: 5.8,
    activity: "activity/karaoke.JPG",
    video:
      "https://drive.google.com/file/d/10oYGwKd98WB1BC3QbfwQhvJOwNTAjofS/preview",
    videoPortrait: true,
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=4d0512116d38;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "teafactory",
    name: "Tea Factory",
    description: {
      id: "Kalian akan mempelajari proses pembuatan the, mulai dari memetik daun the di greenhouse, hingga proses produksi minuman kemasan menggunakan mesin pabrik.",
      en: "You will learn the tea-making process, from picking the tea leaves in the greenhouse to the process of producing packaged drinks using factory machines.",
    },
    image: "establishment/teh pucuk.png",
    top: 57,
    left: 36,
    width: 10.5,
    height: 8.8,
    activity: "activity/tehpucuk.JPG",
    video:
      "https://drive.google.com/file/d/1IaN8oXdm2x7t00W64AaYFkTGATOtV6xi/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=37eebaddf56e;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "earthquakesurvival",
    name: "Earthquake Survival Institute",
    description: {
      id: "Jadilah seorang yang responsif terhadap force majeure! Ikuti latihan darurat gempa dan kalian akan melakukan misi pencarian, penyelamatan dan pelatihan bertahan hidup. Pelajari juga cara mengurangi risiko selama terjadi gempa bumi.",
      en: "Be responsive to force majeure! Participate in earthquake emergency drills and you will perform search, rescue and survival mission. Learn how to mitigate risk during an earthquake.",
    },
    image: "establishment/Earthquake.png",
    top: 24,
    left: 36,
    width: 18.5,
    height: 9.5,
    activity: "activity/earthquake.JPG",
    video:
      "https://drive.google.com/file/d/1vgixuq9virFDDrc0KUwI1hA9a5COL2QS/preview",
    videoPortrait: true,
    tags: ["TeenZ", "ChildZ"],
    fib: "https://www.fourz.net/Operations/CensusDisplay?p=3231076041a4;Asia/Jakarta;HH:mm;en-US",
  },
  {
    id: "multipurpose",
    name: "Multipurpose ",
    description: {
      id: "Pengunjung dapat Membeli makanan dan kudapan yang akan dinikmati di Multipurpose atau Main Square.",
      en: "Visitors can buy meals and snacks to enjoy in the Multipurpose or Main Square.",
    },
    image: "establishment/Main Square.png",
    top: 72,
    left: 10.5,
    width: 26.1,
    height: 16.6,
    activity: "activity/multipurpose.JPG",
    tags: ["ParentZ", "TeenZ", "ChildZ"],
    menu: "menu/cafetaria.jpg",
  },
];
